name: Generate code coverage badge

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Update coverage badge
    steps:
      - uses: tj-actions/coverage-badge-go@v2.4.1
        with:
          green: 80
          yellow: 60
          text: coverage